Models:
- Config: configs/face_2d_keypoint/topdown_heatmap/aflw/td-hm_hrnetv2-w18_8xb64-60e_aflw-256x256.py
  In Collection: HRNetv2
  Metadata:
    Architecture:
    - HRNetv2
    Training Data: AFLW
  Name: td-hm_hrnetv2-w18_8xb64-60e_aflw-256x256
  Results:
  - Dataset: AFLW
    Metrics:
      NME frontal: 1.27
      NME full: 1.41
    Task: Face 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/face/hrnetv2/hrnetv2_w18_aflw_256x256-f2bbc62b_20210125.pth
