Models:
- Config: configs/face_2d_keypoint/topdown_heatmap/coco_wholebody_face/td-hm_hrnetv2-w18_8xb32-60e_coco-wholebody-face-256x256.py
  In Collection: HRNetv2
  Metadata:
    Architecture:
    - HRNetv2
    Training Data: COCO-WholeBody-Face
  Name: td-hm_hrnetv2-w18_8xb32-60e_coco-wholebody-face-256x256
  Results:
  - Dataset: COCO-WholeBody-Face
    Metrics:
      NME: 0.0569
    Task: Face 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/face/hrnetv2/hrnetv2_w18_coco_wholebody_face_256x256-c1ca469b_20210909.pth
