Models:
- Config: configs/wholebody_2d_keypoint/topdown_heatmap/coco-wholebody/td-hm_hrnet-w32_8xb64-210e_coco-wholebody-256x192.py
  In Collection: HRNet
  Metadata:
    Architecture: &id001
    - HRNet
    Training Data: COCO-WholeBody
  Name: td-hm_hrnet-w32_8xb64-210e_coco-wholebody-256x192
  Results:
  - Dataset: COCO-WholeBody
    Metrics:
      Body AP: 0.678
      Body AR: 0.755
      Face AP: 0.630
      Face AR: 0.708
      Foot AP: 0.543
      Foot AR: 0.661
      Hand AP: 0.467
      Hand AR: 0.566
      Whole AP: 0.536
      Whole AR: 0.636
    Task: Wholebody 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_wholebody_256x192-853765cd_20200918.pth
- Config: configs/wholebody_2d_keypoint/topdown_heatmap/coco-wholebody/td-hm_hrnet-w32_8xb64-210e_coco-wholebody-384x288.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: COCO-WholeBody
  Name: td-hm_hrnet-w32_8xb64-210e_coco-wholebody-384x288
  Results:
  - Dataset: COCO-WholeBody
    Metrics:
      Body AP: 0.700
      Body AR: 0.772
      Face AP: 0.726
      Face AR: 0.783
      Foot AP: 0.585
      Foot AR: 0.691
      Hand AP: 0.515
      Hand AR: 0.603
      Whole AP: 0.586
      Whole AR: 0.673
    Task: Wholebody 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_wholebody_384x288-78cacac3_20200922.pth
- Config: configs/wholebody_2d_keypoint/topdown_heatmap/coco-wholebody/td-hm_hrnet-w48_8xb32-210e_coco-wholebody-256x192.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: COCO-WholeBody
  Name: td-hm_hrnet-w48_8xb32-210e_coco-wholebody-256x192
  Results:
  - Dataset: COCO-WholeBody
    Metrics:
      Body AP: 0.701
      Body AR: 0.776
      Face AP: 0.656
      Face AR: 0.743
      Foot AP: 0.675
      Foot AR: 0.787
      Hand AP: 0.535
      Hand AR: 0.639
      Whole AP: 0.579
      Whole AR: 0.681
    Task: Wholebody 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_wholebody_256x192-643e18cb_20200922.pth
- Config: configs/wholebody_2d_keypoint/topdown_heatmap/coco-wholebody/td-hm_hrnet-w48_8xb32-210e_coco-wholebody-384x288.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: COCO-WholeBody
  Name: td-hm_hrnet-w48_8xb32-210e_coco-wholebody-384x288
  Results:
  - Dataset: COCO-WholeBody
    Metrics:
      Body AP: 0.722
      Body AR: 0.791
      Face AP: 0.776
      Face AR: 0.834
      Foot AP: 0.696
      Foot AR: 0.801
      Hand AP: 0.587
      Hand AR: 0.678
      Whole AP: 0.632
      Whole AR: 0.717
    Task: Wholebody 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_wholebody_384x288-6e061c6a_20200922.pth
