Models:
- Config: configs/face_2d_keypoint/topdown_heatmap/wflw/td-hm_hrnetv2-w18_dark-8xb64-60e_wflw-256x256.py
  In Collection: DarkPose
  Metadata:
    Architecture:
    - HRNetv2
    - DarkPose
    Training Data: WFLW
  Name: td-hm_hrnetv2-w18_dark-8xb64-60e_wflw-256x256
  Results:
  - Dataset: WFLW
    Metrics:
      NME blur: 4.56
      NME expression: 4.29
      NME illumination: 3.96
      NME makeup: 3.89
      NME occlusion: 4.78
      NME pose: 6.98
      NME test: 3.98
    Task: Face 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/face/darkpose/hrnetv2_w18_wflw_256x256_dark-3f8e0c2c_20210125.pth
