Models:
- Config: configs/face_2d_keypoint/topdown_heatmap/cofw/td-hm_hrnetv2-w18_8xb64-60e_cofw-256x256.py
  In Collection: HRNetv2
  Metadata:
    Architecture:
    - HRNetv2
    Training Data: COFW
  Name: td-hm_hrnetv2-w18_8xb64-60e_cofw-256x256
  Results:
  - Dataset: COFW
    Metrics:
      NME: 3.48
    Task: Face 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/face/hrnetv2/hrnetv2_w18_cofw_256x256-49243ab8_20211019.pth
