Models:
- Config: configs/fashion_2d_keypoint/topdown_heatmap/deepfashion2/td-hm_res50_6xb64-210e_deepfasion2-short-sleeved-shirt-256x192.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: &id001
    - SimpleBaseline2D
    - ResNet
    Training Data: DeepFashion2
  Name: td-hm_res50_6xb64-210e_deepfasion2-short-sleeved-shirt-256x192
  Results:
  - Dataset: DeepFashion2
    Metrics:
      AUC: 0.703
      EPE: 10.2
      PCK@0.2: 0.988
    Task: Fashion 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/fashion/resnet/res50_deepfashion2_short_sleeved_shirt_256x192-21e1c5da_20221208.pth
- Config: configs/fashion_2d_keypoint/topdown_heatmap/deepfashion2/td-hm_res50_8xb64-210e_deepfasion2-long-sleeved-shirt-256x192.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: DeepFashion2
  Name: td-hm_res50_8xb64-210e_deepfasion2-long-sleeved-shirt-256x192
  Results:
  - Dataset: DeepFashion2
    Metrics:
      AUC: 0.587
      EPE: 16.5
      PCK@0.2: 0.973
    Task: Fashion 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/fashion/resnet/res50_deepfashion2_long_sleeved_shirt_256x192-8679e7e3_20221208.pth
- Config: configs/fashion_2d_keypoint/topdown_heatmap/deepfashion2/td-hm_res50_8xb64-210e_deepfasion2-short-sleeved-outwear-256x192.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: DeepFashion2
  Name: td-hm_res50_8xb64-210e_deepfasion2-short-sleeved-outwear-256x192
  Results:
  - Dataset: DeepFashion2
    Metrics:
      AUC: 0.408
      EPE: 24.0
      PCK@0.2: 0.966
    Task: Fashion 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/fashion/resnet/res50_deepfashion2_short_sleeved_outwear_256x192-a04c1298_20221208.pth
- Config: configs/fashion_2d_keypoint/topdown_heatmap/deepfashion2/td-hm_res50_8xb64-210e_deepfasion2-long-sleeved-outwear-256x192.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: DeepFashion2
  Name: td-hm_res50_8xb64-210e_deepfasion2-long-sleeved-outwear-256x192
  Results:
  - Dataset: DeepFashion2
    Metrics:
      AUC: 0.517
      EPE: 18.1
      PCK@0.2: 0.987
    Task: Fashion 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/fashion/resnet/res50_deepfashion2_long_sleeved_outwear_256x192-31fbaecf_20221208.pth
- Config: configs/fashion_2d_keypoint/topdown_heatmap/deepfashion2/td-hm_res50_4xb64-210e_deepfasion2-vest-256x192.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: DeepFashion2
  Name: td-hm_res50_4xb64-210e_deepfasion2-vest-256x192
  Results:
  - Dataset: DeepFashion2
    Metrics:
      AUC: 0.643
      EPE: 12.7
      PCK@0.2: 0.981
    Task: Fashion 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/fashion/resnet/res50_deepfashion2_vest_256x192-4c48d05c_20221208.pth
- Config: configs/fashion_2d_keypoint/topdown_heatmap/deepfashion2/td-hm_res50_4xb64-210e_deepfasion2-sling-256x192.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: DeepFashion2
  Name: td-hm_res50_4xb64-210e_deepfasion2-sling-256x192
  Results:
  - Dataset: DeepFashion2
    Metrics:
      AUC: 0.557
      EPE: 21.6
      PCK@0.2: 0.94
    Task: Fashion 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/fashion/resnet/res50_deepfashion2_sling_256x192-ebb2b736_20221208.pth
- Config: configs/fashion_2d_keypoint/topdown_heatmap/deepfashion2/td-hm_res50_3xb64-210e_deepfasion2-shorts-256x192.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: DeepFashion2
  Name: td-hm_res50_3xb64-210e_deepfasion2-shorts-256x192
  Results:
  - Dataset: DeepFashion2
    Metrics:
      AUC: 0.682
      EPE: 12.4
      PCK@0.2: 0.975
    Task: Fashion 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/fashion/resnet/res50_deepfashion2_shorts_256x192-9ab23592_20221208.pth
- Config: configs/fashion_2d_keypoint/topdown_heatmap/deepfashion2/td-hm_res50_2xb64-210e_deepfasion2-trousers-256x192.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: DeepFashion2
  Name: td-hm_res50_2xb64-210e_deepfasion2-trousers-256x192
  Results:
  - Dataset: DeepFashion2
    Metrics:
      AUC: 0.625
      EPE: 14.8
      PCK@0.2: 0.973
    Task: Fashion 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/fashion/resnet/res50_deepfashion2_trousers_256x192-3e632257_20221208.pth
- Config: configs/fashion_2d_keypoint/topdown_heatmap/deepfashion2/td-hm_res50_1xb64-210e_deepfasion2-skirt-256x192.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: DeepFashion2
  Name: td-hm_res50_1xb64-210e_deepfasion2-skirt-256x192
  Results:
  - Dataset: DeepFashion2
    Metrics:
      AUC: 0.653
      EPE: 16.6
      PCK@0.2: 0.952
    Task: Fashion 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/fashion/resnet/res50_deepfashion2_skirt_256x192-09573469_20221208.pth
- Config: configs/fashion_2d_keypoint/topdown_heatmap/deepfashion2/td-hm_res50_4xb64-210e_deepfasion2-short-sleeved-dress-256x192.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: DeepFashion2
  Name: td-hm_res50_4xb64-210e_deepfasion2-short-sleeved-dress-256x192
  Results:
  - Dataset: DeepFashion2
    Metrics:
      AUC: 0.603
      EPE: 15.6
      PCK@0.2: 0.98
    Task: Fashion 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/fashion/resnet/res50_deepfashion2_short_sleeved_dress_256x192-1345b07a_20221208.pth
- Config: configs/fashion_2d_keypoint/topdown_heatmap/deepfashion2/td-hm_res50_1xb64-210e_deepfasion2-long-sleeved-dress-256x192.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: DeepFashion2
  Name: td-hm_res50_1xb64-210e_deepfasion2-long-sleeved-dress-256x192
  Results:
  - Dataset: DeepFashion2
    Metrics:
      AUC: 0.518
      EPE: 20.1
      PCK@0.2: 0.976
    Task: Fashion 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/fashion/resnet/res50_deepfashion2_long_sleeved_dress_256x192-87bac74e_20221208.pth
- Config: configs/fashion_2d_keypoint/topdown_heatmap/deepfashion2/td-hm_res50_1xb64-210e_deepfasion2-vest-dress-256x192.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: DeepFashion2
  Name: td-hm_res50_1xb64-210e_deepfasion2-vest-dress-256x192
  Results:
  - Dataset: DeepFashion2
    Metrics:
      AUC: 0.6
      EPE: 16.0
      PCK@0.2: 0.98
    Task: Fashion 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/fashion/resnet/res50_deepfashion2_vest_dress_256x192-fb3fbd6f_20221208.pth
- Config: configs/fashion_2d_keypoint/topdown_heatmap/deepfashion2/td-hm_res50_4xb64-210e_deepfasion2-sling-dress-256x192.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: DeepFashion2
  Name: td-hm_res50_4xb64-210e_deepfasion2-sling-dress-256x192
  Results:
  - Dataset: DeepFashion2
    Metrics:
      AUC: 0.544
      EPE: 19.5
      PCK@0.2: 0.967
    Task: Fashion 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/fashion/resnet/res50_deepfashion2_sling_dress_256x192-8ebae0eb_20221208.pth
