Models:
- Config: configs/face_2d_keypoint/rtmpose/coco_wholebody_face/rtmpose-m_8xb32-60e_coco-wholebody-face-256x256.py
  In Collection: RTMPose
  Metadata:
    Architecture:
    - RTMPose
    Training Data: COCO-WholeBody-Face
  Name: rtmpose-m_8xb32-60e_coco-wholebody-face-256x256
  Results:
  - Dataset: COCO-WholeBody-Face
    Metrics:
      NME: 0.0466
    Task: Face 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/rtmpose-m_simcc-coco-wholebody-face_pt-aic-coco_60e-256x256-62026ef2_20230228.pth
