Models:
- Config: configs/hand_2d_keypoint/topdown_heatmap/onehand10k/td-hm_hrnetv2-w18_8xb64-210e_onehand10k-256x256.py
  In Collection: HRNetv2
  Metadata:
    Architecture:
    - HRNetv2
    Training Data: OneHand10K
  Name: td-hm_hrnetv2-w18_8xb64-210e_onehand10k-256x256
  Results:
  - Dataset: OneHand10K
    Metrics:
      AUC: 0.567
      EPE: 24.26
      PCK@0.2: 0.99
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/hrnetv2/hrnetv2_w18_onehand10k_256x256-30bc9c6b_20210330.pth
