Models:
- Config: configs/body_2d_keypoint/topdown_heatmap/mpii/td-hm_hrnet-w32_dark-8xb64-210e_mpii-256x256.py
  In Collection: DarkPose
  Metadata:
    Architecture: &id001
    - HRNet
    - DarkPose
    Training Data: MPII
  Name: td-hm_hrnet-w32_dark-8xb64-210e_mpii-256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.904
      Mean@0.1: 0.354
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_mpii_256x256_dark-f1601c5b_20200927.pth
- Config: configs/body_2d_keypoint/topdown_heatmap/mpii/td-hm_hrnet-w48_dark-8xb64-210e_mpii-256x256.py
  In Collection: DarkPose
  Metadata:
    Architecture: *id001
    Training Data: MPII
  Name: td-hm_hrnet-w48_dark-8xb64-210e_mpii-256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.905
      Mean@0.1: 0.36
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_mpii_256x256_dark-0decd39f_20200927.pth
