Models:
- Config: configs/body_2d_keypoint/topdown_heatmap/mpii/td-hm_litehrnet-18_8xb64-210e_mpii-256x256.py
  In Collection: LiteHRNet
  Metadata:
    Architecture: &id001
    - LiteHRNet
    Training Data: MPII
  Name: td-hm_litehrnet-18_8xb64-210e_mpii-256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.859
      Mean@0.1: 0.26
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/litehrnet/litehrnet18_mpii_256x256-cabd7984_20210623.pth
- Config: configs/body_2d_keypoint/topdown_heatmap/mpii/td-hm_litehrnet-30_8xb64-210e_mpii-256x256.py
  In Collection: LiteHRNet
  Metadata:
    Architecture: *id001
    Training Data: MPII
  Name: td-hm_litehrnet-30_8xb64-210e_mpii-256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.869
      Mean@0.1: 0.271
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/litehrnet/litehrnet30_mpii_256x256-faae8bd8_20210622.pth
