Models:
- Config: configs/body_2d_keypoint/topdown_heatmap/mpii/td-hm_mobilenetv2_8xb64-210e_mpii-256x256.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture:
    - SimpleBaseline2D
    - MobilenetV2
    Training Data: MPII
  Name: td-hm_mobilenetv2_8xb64-210e_mpii-256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.854
      Mean@0.1: 0.234
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/mobilenetv2/mobilenetv2_mpii_256x256-e068afa7_20200812.pth
