Models:
- Config: configs/body_2d_keypoint/topdown_heatmap/mpii/td-hm_resnext152_8xb32-210e_mpii-256x256.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture:
    - SimpleBaseline2D
    - ResNext
    Training Data: MPII
  Name: td-hm_resnext152_8xb32-210e_mpii-256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.887
      Mean@0.1: 0.294
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnext/resnext152_mpii_256x256-df302719_20200927.pth
