Models:
- Config: configs/body_2d_keypoint/topdown_heatmap/mpii/td-hm_res50_8xb64-210e_mpii-256x256.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: &id001
    - SimpleBaseline2D
    - ResNet
    Training Data: MPII
  Name: td-hm_res50_8xb64-210e_mpii-256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.882
      Mean@0.1: 0.286
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_mpii_256x256-418ffc88_20200812.pth
- Config: configs/body_2d_keypoint/topdown_heatmap/mpii/td-hm_res101_8xb64-210e_mpii-256x256.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: MPII
  Name: td-hm_res101_8xb64-210e_mpii-256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.888
      Mean@0.1: 0.29
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res101_mpii_256x256-416f5d71_20200812.pth
- Config: configs/body_2d_keypoint/topdown_heatmap/mpii/td-hm_res152_8xb32-210e_mpii-256x256.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: MPII
  Name: td-hm_res152_8xb32-210e_mpii-256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.889
      Mean@0.1: 0.303
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res152_mpii_256x256-3ecba29d_20200812.pth
