Models:
- Config: configs/hand_2d_keypoint/topdown_heatmap/coco_wholebody_hand/td-hm_hourglass52_8xb32-210e_coco-wholebody-hand-256x256.py
  In Collection: Hourglass
  Metadata:
    Architecture:
    - Hourglass
    Training Data: COCO-WholeBody-Hand
  Name: td-hm_hourglass52_8xb32-210e_coco-wholebody-hand-256x256
  Results:
  - Dataset: COCO-WholeBody-Hand
    Metrics:
      AUC: 0.835
      EPE: 4.54
      PCK@0.2: 0.804
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/hourglass/hourglass52_coco_wholebody_hand_256x256-7b05c6db_20210909.pth
