Models:
- Config: configs/hand_2d_keypoint/topdown_heatmap/coco_wholebody_hand/td-hm_hrnetv2-w18_8xb32-210e_coco-wholebody-hand-256x256.py
  In Collection: HRNetv2
  Metadata:
    Architecture:
    - HRNetv2
    Training Data: COCO-WholeBody-Hand
  Name: td-hm_hrnetv2-w18_8xb32-210e_coco-wholebody-hand-256x256
  Results:
  - Dataset: COCO-WholeBody-Hand
    Metrics:
      AUC: 0.84
      EPE: 4.39
      PCK@0.2: 0.813
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/hrnetv2/hrnetv2_w18_coco_wholebody_hand_256x256-1c028db7_20210908.pth
