Models:
- Config: configs/hand_2d_keypoint/topdown_heatmap/coco_wholebody_hand/td-hm_mobilenetv2_8xb32-210e_coco-wholebody-hand-256x256.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture:
    - SimpleBaseline2D
    - MobilenetV2
    Training Data: COCO-WholeBody-Hand
  Name: td-hm_mobilenetv2_8xb32-210e_coco-wholebody-hand-256x256
  Results:
  - Dataset: COCO-WholeBody-Hand
    Metrics:
      AUC: 0.829
      EPE: 4.77
      PCK@0.2: 0.795
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/mobilenetv2/mobilenetv2_coco_wholebody_hand_256x256-06b8c877_20210909.pth
