Models:
- Config: configs/face_2d_keypoint/rtmpose/lapa/rtmpose-m_8xb64-120e_lapa-256x256.py
  In Collection: RTMPose
  Alias: face
  Metadata:
    Architecture:
    - RTMPose
    Training Data: LaPa
  Name: rtmpose-m_8xb64-120e_lapa-256x256
  Results:
  - Dataset: WFLW
    Metrics:
      NME: 1.29
    Task: Face 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/rtmpose-m_simcc-lapa_pt-aic-coco_120e-256x256-762b1ae2_20230422.pth
