Collections:
- Name: Hourglass
  Paper:
    Title: Stacked hourglass networks for human pose estimation
    URL: https://link.springer.com/chapter/10.1007/978-3-319-46484-8_29
  README:  https://github.com/open-mmlab/mmpose/blob/main/docs/src/papers/backbones/hourglass.md
Models:
- Config: configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hourglass52_8xb32-210e_coco-256x256.py
  In Collection: Hourglass
  Metadata:
    Architecture: &id001
    - Hourglass
    Training Data: COCO
  Name: td-hm_hourglass52_8xb32-210e_coco-256x256
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.726
      AP@0.5: 0.896
      AP@0.75: 0.799
      AR: 0.780
      AR@0.5: 0.934
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hourglass/hourglass52_coco_256x256-4ec713ba_20200709.pth
- Config: configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hourglass52_8xb32-210e_coco-384x384.py
  In Collection: Hourglass
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: td-hm_hourglass52_8xb32-210e_coco-384x384
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.746
      AP@0.5: 0.900
      AP@0.75: 0.812
      AR: 0.797
      AR@0.5: 0.939
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hourglass/hourglass52_coco_384x384-be91ba2b_20200812.pth
