Collections:
- Name: HRFormer
  Paper:
    Title: 'HRFormer: High-Resolution Vision Transformer for Dense Predict'
    URL: https://proceedings.neurips.cc/paper/2021/hash/3bbfdde8842a5c44a0323518eec97cbe-Abstract.html
  README: https://github.com/open-mmlab/mmpose/blob/main/docs/src/papers/backbones/hrformer.md
Models:
- Config: configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrformer-small_8xb32-210e_coco-256x192.py
  In Collection: HRFormer
  Metadata:
    Architecture: &id001
    - HRFormer
    Training Data: COCO
  Name: td-hm_hrformer-small_8xb32-210e_coco-256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.738
      AP@0.5: 0.904
      AP@0.75: 0.812
      AR: 0.793
      AR@0.5: 0.941
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrformer/hrformer_small_coco_256x192-5310d898_20220316.pth
- Config: configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrformer-small_8xb32-210e_coco-384x288.py
  In Collection: HRFormer
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: td-hm_hrformer-small_8xb32-210e_coco-384x288
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.757
      AP@0.5: 0.905
      AP@0.75: 0.824
      AR: 0.807
      AR@0.5: 0.941
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrformer/hrformer_small_coco_384x288-98d237ed_20220316.pth
- Config: configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrformer-base_8xb32-210e_coco-256x192.py
  In Collection: HRFormer
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: td-hm_hrformer-base_8xb32-210e_coco-256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.754
      AP@0.5: 0.906
      AP@0.75: 0.827
      AR: 0.807
      AR@0.5: 0.943
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrformer/hrformer_base_coco_256x192-6f5f1169_20220316.pth
- Config: configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrformer-base_8xb32-210e_coco-384x288.py
  In Collection: HRFormer
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: td-hm_hrformer-base_8xb32-210e_coco-384x288
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.774
      AP@0.5: 0.909
      AP@0.75: 0.842
      AR: 0.823
      AR@0.5: 0.945
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrformer/hrformer_base_coco_384x288-ecf0758d_20220316.pth
