Collections:
- Name: UDP
  Paper:
    Title: 'The Devil Is in the Details: Delving Into Unbiased Data Processing for
      Human Pose Estimation'
    URL: http://openaccess.thecvf.com/content_CVPR_2020/html/Huang_The_Devil_Is_in_the_Details_Delving_Into_Unbiased_Data_CVPR_2020_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/main/docs/src/papers/techniques/udp.md
Models:
- Config: configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w32_udp-8xb64-210e_coco-256x192.py
  In Collection: UDP
  Metadata:
    Architecture: &id001
    - HRNet
    - UDP
    Training Data: COCO
  Name: td-hm_hrnet-w32_udp-8xb64-210e_coco-256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.762
      AP@0.5: 0.907
      AP@0.75: 0.829
      AR: 0.810
      AR@0.5: 0.942
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/v1/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w32_udp-8xb64-210e_coco-256x192-73ede547_20220914.pth
- Config: configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w32_udp-8xb64-210e_coco-384x288.py
  In Collection: UDP
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: td-hm_hrnet-w32_udp-8xb64-210e_coco-384x288
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.768
      AP@0.5: 0.909
      AP@0.75: 0.832
      AR: 0.815
      AR@0.5: 0.945
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/v1/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w32_udp-8xb64-210e_coco-384x288-9a3f7c85_20220914.pth
- Config: configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w48_udp-8xb32-210e_coco-256x192.py
  In Collection: UDP
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: td-hm_hrnet-w48_udp-8xb32-210e_coco-256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.768
      AP@0.5: 0.908
      AP@0.75: 0.833
      AR: 0.817
      AR@0.5: 0.945
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/v1/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w48_udp-8xb32-210e_coco-256x192-3feaef8f_20220913.pth
- Config: configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w48_udp-8xb32-210e_coco-384x288.py
  In Collection: UDP
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: td-hm_hrnet-w48_udp-8xb32-210e_coco-384x288
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.773
      AP@0.5: 0.911
      AP@0.75: 0.836
      AR: 0.821
      AR@0.5: 0.946
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/v1/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w48_udp-8xb32-210e_coco-384x288-70d7ab01_20220913.pth
- Config: configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w32_udp-regress-8xb64-210e_coco-256x192.py
  In Collection: UDP
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: td-hm_hrnet-w32_udp-regress-8xb64-210e_coco-256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.759
      AP@0.5: 0.907
      AP@0.75: 0.827
      AR: 0.813
      AR@0.5: 0.943
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/v1/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w32_udp-regress-8xb64-210e_coco-256x192-9c0b77b4_20220926.pth
