Collections:
- Name: RLE
  Paper:
    Title: Human pose regression with residual log-likelihood estimation
    URL: https://arxiv.org/abs/2107.11291
  README: https://github.com/open-mmlab/mmpose/blob/main/docs/src/papers/techniques/rle.md
Models:
- Config: configs/body_2d_keypoint/topdown_regression/coco/td-reg_res50_rle-8xb64-210e_coco-256x192.py
  In Collection: RLE
  Metadata:
    Architecture: &id001
    - DeepPose
    - RLE
    - ResNet
    Training Data: COCO
  Name: td-reg_res50_rle-8xb64-210e_coco-256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.706
      AP@0.5: 0.888
      AP@0.75: 0.776
      AR: 0.753
      AR@0.5: 0.924
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/v1/body_2d_keypoint/topdown_regression/coco/td-reg_res50_rle-8xb64-210e_coco-256x192-d37efd64_20220913.pth
- Config: configs/body_2d_keypoint/topdown_regression/coco/td-reg_res50_rle-pretrained-8xb64-210e_coco-256x192.py
  In Collection: RLE
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: td-reg_res50_rle-pretrained-8xb64-210e_coco-256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.719
      AP@0.5: 0.891
      AP@0.75: 0.788
      AR: 0.764
      AR@0.5: 0.925
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/v1/body_2d_keypoint/topdown_regression/coco/td-reg_res50_rle-pretrained-8xb64-210e_coco-256x192-2cb494ee_20220913.pth
- Config: configs/body_2d_keypoint/topdown_regression/coco/td-reg_res101_rle-8xb64-210e_coco-256x192.py
  In Collection: RLE
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: td-reg_res101_rle-8xb64-210e_coco-256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.722
      AP@0.5: 0.894
      AP@0.75: 0.794
      AR: 0.768
      AR@0.5: 0.93
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/deeppose/deeppose_res101_coco_256x192_rle-16c3d461_20220615.pth
- Config: configs/body_2d_keypoint/topdown_regression/coco/td-reg_res152_rle-8xb64-210e_coco-256x192.py
  In Collection: RLE
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: td-reg_res152_rle-8xb64-210e_coco-256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.731
      AP@0.5: 0.897
      AP@0.75: 0.805
      AR: 0.777
      AR@0.5: 0.933
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/deeppose/deeppose_res152_coco_256x192_rle-c05bdccf_20220615.pth
- Config: configs/body_2d_keypoint/topdown_regression/coco/td-reg_res152_rle-8xb64-210e_coco-384x288.py
  In Collection: RLE
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: td-reg_res152_rle-8xb64-210e_coco-384x288
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.749
      AP@0.5: 0.901
      AP@0.75: 0.815
      AR: 0.793
      AR@0.5: 0.935
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/deeppose/deeppose_res152_coco_384x288_rle-b77c4c37_20220624.pth
