Collections:
- Name: HRNetv2
  Paper:
    Title: Deep High-Resolution Representation Learning for Visual Recognition
    URL: https://ieeexplore.ieee.org/abstract/document/9052469/
  README: https://github.com/open-mmlab/mmpose/blob/main/docs/src/papers/backbones/hrnetv2.md
Models:
- Config: configs/face_2d_keypoint/topdown_heatmap/300wlp/td-hm_hrnetv2-w18_8xb64-60e_300wlp-256x256.py
  In Collection: HRNetv2
  Metadata:
    Architecture:
    - HRNetv2
    Training Data: 300W-LP
  Name: td-hm_hrnetv2-w18_8xb64-60e_300wlp-256x256
  Results:
  - Dataset: 300W-LP
    Metrics:
      NME full: 0.0413
    Task: Face 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/v1/face_2d_keypoint/topdown_heatmap/300wlp/hrnetv2_w18_300wlp_256x256-fb433d21_20230922.pth
