Models:
- Config: configs/hand_2d_keypoint/topdown_heatmap/rhd2d/td-hm_hrnetv2-w18_udp-8xb64-210e_rhd2d-256x256.py
  In Collection: UDP
  Metadata:
    Architecture:
    - HRNetv2
    - UDP
    Training Data: RHD
  Name: td-hm_hrnetv2-w18_udp-8xb64-210e_rhd2d-256x256
  Results:
  - Dataset: RHD
    Metrics:
      AUC: 0.902
      EPE: 2.19
      PCKh@0.7: 0.992
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/udp/hrnetv2_w18_rhd2d_256x256_udp-63ba6007_20210330.pth
